# Site settings
name: Vishal Gupta
title: Vishal Gupta | Artificial Intelligence Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://brittanychiang.com/
baseurl: ""
email: brittany.chiang@gmail.com
cover: https://github.com/The-Gupta/The-Gupta.github.io/blob/master/img/headshot.jpg
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://github.com/The-Gupta/The-Gupta.github.io/blob/master/resume.pdf
social:
  - title: email
    url: mailto:vishal.gupta@nitdelhi.ac.in
  - title: github
    url: https://github.com/The-Gupta
  - title: linkedin
    url: https://www.linkedin.com/in/thegupta/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
