# Site settings
name: Vishal Gupta
title: Vishal Gupta | Artificial Intelligence Software Engineer
description: :)
baseurl: ""
email: vishal.gupta@nitdelhi.ac.in
cover: https://github.com/The-Gupta/The-Gupta.github.io/blob/master/myPhoto.jpg
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://github.com/The-Gupta/The-Gupta.github.io/blob/master/myProfile.pdf
social:
  - title: email
    url: mailto:vishal.gupta@nitdelhi.ac.in
  - title: github
    url: https://github.com/The-Gupta
  - title: linkedin
    url: https://www.linkedin.com/in/thegupta/
  - title: analytics vidhya
    url: https://datahack.analyticsvidhya.com/user/profile/TheGupta/
  - title: HackerRank
    url: https://www.hackerrank.com/TheGupta
  - title: angel.co
    url: http://angel.co/thegupta/
  - title: Stack Overflow
    url: https://stackoverflow.com/users/8321339/vishal-gupta/
  - title: Quora
    url: https://www.quora.com/profile/Vishal-Gupta-50/
  - title: Medium
    url: https://medium.com/@vishal.gupta_49292/
  - title: Twitter
    url: https://twitter.com/vishalbuck/
  - title: Facebook
    url: http://facebook.com/yoyobuck/
     
# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
